
CREATE DATABASE videoSys 
GO

USE videoSys
GO

CREATE TABLE VIDEO
(
	VideoID NVARCHAR(50) PRIMARY KEY,
	Titile NVARCHAR(50) NOT NULL,
	Poster NVARCHAR(50) NOT NULL,
	Veiws INT NOT NULL,
	Descriptionn NVARCHAR(50) NOT NULL,
	Active BIT NOT NULL
)

GO
CREATE TABLE USERS
(
	UserID NVARCHAR(50) PRIMARY KEY,
	Passwords NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	Fullname NVARCHAR(50) NOT NULL
)

GO
CREATE TABLE FAVORITE
(
	FovoriteID NVARCHAR(50) PRIMARY KEY,
	UserID NVARCHAR(50)  NOT NULL,
	VideoID NVARCHAR(50) NOT NULL,
	LikeDate Date NOT NULL

	FOREIGN KEY (UserID) REFERENCES dbo.USERS(UserID)  ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (VideoID) REFERENCES dbo.VIDEO(VideoID)  ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TABLE SHARE
(
	ShareID NVARCHAR(50) PRIMARY KEY,
	UserID NVARCHAR(50) NOT NULL,
	VideoID NVARCHAR(50) NOT NULL,
	Emails NVARCHAR(50) NOT NULL,
	ShareDate Date NOT NULL

	FOREIGN KEY (UserID) REFERENCES dbo.USERS(UserID)  ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (VideoID) REFERENCES dbo.VIDEO(VideoID)  ON UPDATE CASCADE ON DELETE CASCADE
)
GO
CREATE TABLE ADMINS
(
	AdminID NVARCHAR(50) PRIMARY KEY,
	Passwords NVARCHAR(50) NOT NULL,
	Emails NVARCHAR(50) NOT NULL

)
GO 
CREATE TABLE VIDEO_MANAGEMENT
(
	AdminID NVARCHAR(50),
	VideoID NVARCHAR(50),
	PRIMARY KEY(AdminID , VideoID),
	FOREIGN KEY (AdminID) REFERENCES dbo.ADMINS(AdminID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (VideoID) REFERENCES dbo.VIDEO(VideoID)  ON UPDATE CASCADE ON DELETE CASCADE
)
GO 
CREATE TABLE USER_MANAGEMENT
(
	AdminID NVARCHAR(50),
	USERID NVARCHAR(50),
	PRIMARY KEY(AdminID , USERID),
	FOREIGN KEY (AdminID) REFERENCES dbo.ADMINS(AdminID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (UserID) REFERENCES dbo.USERS(UserID)  ON UPDATE CASCADE ON DELETE CASCADE
)
